### ISSUE TITLE
requirements.txt file & License

### ISSUE THREAD

**Issue by FelixWeichselgartner** [fidoriel/pyMCP23017#1]
Hi,

saw your project.

A requirements.txt file with the content:

smbus

would be nice for installation.

Greetings from Germany

**Comment by FelixWeichselgartner** [comment]
Also it would be nice if you added a license - so people can actually use the code

**Comment by fidoriel** [comment]
Hi Felix,

I have added the license and requirement files and changed the readme. By the way, a license has existed in the mail file. Maybe I have time during the Christmas hollidays to review and shrike the code.

Best fidoriel
